package com.houvven.guise.util.android

import android.graphics.Point
import android.graphics.PointF
import java.util.Random
import java.util.UUID
import kotlin.math.roundToInt

/**
 * Utility object for generating random data commonly needed when spoofing device
 * identity attributes such as MAC addresses, IMEI numbers, phone numbers,
 * fingerprints, and GPS coordinates.
 */
object Randoms {

    /**
     * Generates a random alphanumeric string of the specified [length].
     *
     * Each character is randomly chosen from uppercase letters (A-Z),
     * lowercase letters (a-z), or digits (0-9) with equal probability.
     *
     * @param length the desired length of the output string.
     * @return a random alphanumeric string.
     */
    fun randomString(length: Int): String {
        val random = Random()
        val sb = StringBuilder()
        (0 until length).forEach { _ ->
            val number = random.nextInt(3)
            var result: Long = 0
            when (number) {
                // Uppercase letter (ASCII 65-90)
                0 -> result = (Math.random() * 25 + 65).roundToInt().toLong()
                // Lowercase letter (ASCII 97-122)
                1 -> result = (Math.random() * 25 + 97).roundToInt().toLong()
                // Digit (ASCII 48-57)
                2 -> result = (Math.random() * 9 + 48).roundToInt().toLong()
            }
            sb.append(result.toChar())
        }
        return sb.toString()
    }

    /**
     * Generates a random integer with the specified number of digits.
     *
     * Each digit is independently and randomly chosen from 0-8 (inclusive).
     * Leading zeros are possible since each digit is generated independently.
     *
     * @param length the number of digits in the generated integer.
     * @return a random integer with [length] digits.
     */
    fun randomInt(length: Int): Int {
        val random = Random()
        val sb = StringBuilder()
        (0 until length).forEach { _ ->
            val number = random.nextInt(9)
            sb.append(number)
        }
        return sb.toString().toInt()
    }

    /**
     * Generates a random alphanumeric string with a random length between 10 and 99.
     *
     * The length itself is a two-digit random number generated by [randomInt].
     *
     * @return a random string whose length is in the range [10, 99].
     */
    fun randomString(): String {
        return randomString(randomInt(2))
    }


    /**
     * Generates a random UUID string.
     *
     * @return a standard UUID string in the format `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`.
     */
    fun uuid(): String {
        return UUID.randomUUID().toString()
    }

    /**
     * Generates a random UUID string with all dashes removed.
     *
     * @return a 32-character hexadecimal UUID string without dashes.
     */
    fun uuidNoDash(): String {
        return uuid().replace("-", "")
    }

    /**
     * Generates a random MAC address in colon-separated hexadecimal format.
     *
     * The format is `XX:XX:XX:XX:XX:XX` where each `XX` is a two-character
     * random alphanumeric pair.
     *
     * @return a random MAC address string (e.g. `A3:bF:92:c1:D4:e7`).
     */
    fun randomMacAddress(): String {
        val mac = StringBuilder()
        (0 until 6).forEach { _ ->
            mac.append(randomString(2))
            mac.append(":")
        }
        return mac.substring(0, mac.length - 1)
    }


    /**
     * Generates a random 15-digit IMEI number.
     *
     * Each digit is independently and randomly chosen. Note that the generated
     * value does not include a Luhn check digit and therefore may not be a
     * technically valid IMEI.
     *
     * @return a 15-digit numeric string representing a fake IMEI.
     */
    fun randomIMEI(): String {
        val imei = StringBuilder()
        (0 until 15).forEach { _ ->
            imei.append(randomInt(1))
        }
        return imei.toString()
    }

    /**
     * Generates a random Chinese mobile phone number.
     *
     * The number always starts with `1` followed by 10 random digits,
     * producing a total length of 11 digits.
     *
     * @return a random phone number string (e.g. `13812345678`).
     */
    fun randomPhoneNum(): String {
        val phoneNum = StringBuilder()
        phoneNum.append("1")
        (0 until 10).forEach { _ ->
            phoneNum.append(randomInt(1))
        }
        return phoneNum.toString()
    }

    /**
     * Generates a random Android device fingerprint string.
     *
     * The format mimics a real build fingerprint:
     * `<brand>/<product>/<device>:<major>/<build>/<tag>:user/release-keys`
     *
     * @return a random fingerprint string (e.g. `AbCdE/FghijKl/Mnop:7/QRST/Uvwx:user/release-keys`).
     */
    fun randomFingerPrint(): String {
        val random = Random()
        val fingerprint = StringBuilder()
        fingerprint.append(randomString(5))
        fingerprint.append("/")
        fingerprint.append(randomString(6))
        fingerprint.append("/")
        fingerprint.append(randomString(4))
        fingerprint.append(":")
        fingerprint.append(randomInt(1))
        fingerprint.append("/")
        fingerprint.append(randomString(4))
        fingerprint.append("/")
        fingerprint.append(randomString(4))
        fingerprint.append(":")
        fingerprint.append("user/release-keys")
        return fingerprint.toString()
    }


    /**
     * Generates a random geographic coordinate pair.
     *
     * - Latitude (`x`) is in the range [0, 120) with a fractional component.
     * - Longitude (`y`) is in the range [0, 30) with a fractional component.
     *
     * Note: the returned [PointF] uses `x` for latitude and `y` for longitude
     * for convenience; this is **not** standard geographic convention.
     *
     * @return a [PointF] where `x` is latitude and `y` is longitude.
     */
    fun randomLatLac(): PointF {
        val random = Random()
        val lat = random.nextInt(120) + random.nextFloat()
        val lac = random.nextInt(30) + random.nextFloat()
        return PointF(lat, lac)
    }

}
